<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; QC y preprocesamiento – Proyecto Carpio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/05_dada2_inferencia_asv.html" rel="next">
<link href="../chapters/03_flujo_bioinformatico.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-4d9afe2b8d18ee9fa5d0d57b5ed4214d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-7e34ecb6a0e7991f0346b0751d4a7c3f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-0dd2bd5de344125cf763a379ddc3eb04.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/04_control_calidad_preprocesamiento.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">QC y preprocesamiento</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Proyecto Carpio</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dcosimber/carpio2" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen técnico</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01_introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción, antecedentes y objetivos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02_diseno_experimental.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Diseño experimental y muestras</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03_flujo_bioinformatico.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Flujo bioinformático</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04_control_calidad_preprocesamiento.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">QC y preprocesamiento</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05_dada2_inferencia_asv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">DADA2 e inferencia de ASV</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06_taxonomia_controles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxonomía, controles y decontaminación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07_reproducibilidad_ensayos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reproducibilidad entre ensayos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08_resultados_microbiologicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Resultados microbiológicos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09_asociaciones_clinicas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Asociaciones clínicas agregadas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10_conclusiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Conclusiones y próximos pasos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11_referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Reproducibilidad y actualización manual</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../appendices/data_availability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Disponibilidad de datos y licencias</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#auditoría-de-bibliotecas-y-pares-fastq" id="toc-auditoría-de-bibliotecas-y-pares-fastq" class="nav-link active" data-scroll-target="#auditoría-de-bibliotecas-y-pares-fastq"><span class="header-section-number">4.1</span> Auditoría de bibliotecas y pares FASTQ</a></li>
  <li><a href="#informes-de-qc-y-multiqc" id="toc-informes-de-qc-y-multiqc" class="nav-link" data-scroll-target="#informes-de-qc-y-multiqc"><span class="header-section-number">4.2</span> Informes de QC y MultiQC</a></li>
  <li><a href="#recorte-y-verificación-de-primers" id="toc-recorte-y-verificación-de-primers" class="nav-link" data-scroll-target="#recorte-y-verificación-de-primers"><span class="header-section-number">4.3</span> Recorte y verificación de primers</a></li>
  <li><a href="#exploración-y-elección-de-la-estrategia-de-recorte" id="toc-exploración-y-elección-de-la-estrategia-de-recorte" class="nav-link" data-scroll-target="#exploración-y-elección-de-la-estrategia-de-recorte"><span class="header-section-number">4.4</span> Exploración y elección de la estrategia de recorte</a></li>
  <li><a href="#profundidad-de-secuenciación-de-las-biopsias-repetidas" id="toc-profundidad-de-secuenciación-de-las-biopsias-repetidas" class="nav-link" data-scroll-target="#profundidad-de-secuenciación-de-las-biopsias-repetidas"><span class="header-section-number">4.5</span> Profundidad de secuenciación de las biopsias repetidas</a></li>
  <li><a href="#auditoría-integral-de-fastqcmultiqc" id="toc-auditoría-integral-de-fastqcmultiqc" class="nav-link" data-scroll-target="#auditoría-integral-de-fastqcmultiqc"><span class="header-section-number">4.6</span> Auditoría integral de FastQC/MultiQC</a>
  <ul class="collapse">
  <li><a href="#estados-fastqc-y-alcance-de-cada-módulo" id="toc-estados-fastqc-y-alcance-de-cada-módulo" class="nav-link" data-scroll-target="#estados-fastqc-y-alcance-de-cada-módulo"><span class="header-section-number">4.6.1</span> Estados FastQC y alcance de cada módulo</a></li>
  <li><a href="#calidad-longitud-y-composición" id="toc-calidad-longitud-y-composición" class="nav-link" data-scroll-target="#calidad-longitud-y-composición"><span class="header-section-number">4.6.2</span> Calidad, longitud y composición</a></li>
  <li><a href="#por-qué-no-se-truncó-por-posición" id="toc-por-qué-no-se-truncó-por-posición" class="nav-link" data-scroll-target="#por-qué-no-se-truncó-por-posición"><span class="header-section-number">4.6.3</span> Por qué no se truncó por posición</a></li>
  <li><a href="#duplicación-secuencias-sobrerrepresentadas-y-adaptadores" id="toc-duplicación-secuencias-sobrerrepresentadas-y-adaptadores" class="nav-link" data-scroll-target="#duplicación-secuencias-sobrerrepresentadas-y-adaptadores"><span class="header-section-number">4.6.4</span> Duplicación, secuencias sobrerrepresentadas y adaptadores</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dcosimber/carpio2/blob/main/chapters/04_control_calidad_preprocesamiento.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">QC y preprocesamiento</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="auditoría-de-bibliotecas-y-pares-fastq" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="auditoría-de-bibliotecas-y-pares-fastq"><span class="header-section-number">4.1</span> Auditoría de bibliotecas y pares FASTQ</h2>
<p>Se validaron 198 registros técnicos y 396 FASTQ: 46 bibliotecas del ensayo <code>pilot</code> y 152 del ensayo <code>current</code>. La validación de entrada confirmó un <code>fastq_id</code> único por archivo técnico, un único par R1/R2 por biblioteca y 396/396 coincidencias MD5 entre el inventario fuente y el destino de análisis. No se identificaron FASTQ no referenciados. FastQC y MultiQC se ejecutaron antes y después del recorte de primers; por diseño, los conteos de R1 y R2 coinciden en cada biblioteca.</p>
<p>Los FASTQ raw y los controles negativos son inputs inmutables: las copias recortadas son derivados trazables y no sustituyen los archivos de origen. Esta distinción es importante para interpretar los capítulos siguientes: los controles se conservan en la tabla canónica para QC, pero todavía no autorizan una exclusión, una inferencia de contaminantes ni una comparación biológica.</p>
<p>El resumen de bibliotecas y pares de lecturas se presenta en la <a href="#tbl-preprocessing-summary" class="quarto-xref">Tabla&nbsp;<span>4.1</span></a>.</p>
<div id="tbl-preprocessing-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-preprocessing-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.1: Bibliotecas y pares de lecturas antes y después del recorte de primers por secuencia. Las profundidades son idénticas porque no se descartó ningún par.
</figcaption>
<div aria-describedby="tbl-preprocessing-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th style="text-align: right;">Bibliotecas</th>
<th style="text-align: right;">Pares de lecturas crudos</th>
<th style="text-align: right;">Pares tras recorte</th>
<th style="text-align: right;">Retención de pares</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Piloto</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">30,06 millones</td>
<td style="text-align: right;">30,06 millones</td>
<td style="text-align: right;">100,00 %</td>
</tr>
<tr class="even">
<td>Ampliado actual</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">29,91 millones</td>
<td style="text-align: right;">29,91 millones</td>
<td style="text-align: right;">100,00 %</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>198</strong></td>
<td style="text-align: right;"><strong>59,97 millones</strong></td>
<td style="text-align: right;"><strong>59,97 millones</strong></td>
<td style="text-align: right;"><strong>100,00 %</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Las profundidades agregadas por tipo de biblioteca están disponibles en las tablas de <a href="../tables/04_control_calidad_preprocesamiento/Table-4.1-profundidad-bibliotecas-crudas.tsv">FASTQ crudos</a> y <a href="../tables/04_control_calidad_preprocesamiento/Table-4.1-profundidad-bibliotecas-recortadas.tsv">FASTQ recortados</a>.</p>
<div id="tbl-library-scope" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-library-scope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.2: Alcance técnico de las bibliotecas. Las ocho biopsias de <code>pilot</code> se conservan como pares de sensibilidad respecto al ensayo ampliado, no como réplicas biológicas independientes.
</figcaption>
<div aria-describedby="tbl-library-scope-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th>Tipo técnico</th>
<th style="text-align: right;">Bibliotecas</th>
<th style="text-align: right;">Pares crudos</th>
<th>Papel en esta etapa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Piloto</td>
<td>Biopsias</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">11.815.341</td>
<td>Biopsias repetidas; QC técnico pareado.</td>
</tr>
<tr class="even">
<td>Piloto</td>
<td>Controles positivos</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">18.249.198</td>
<td>Recuperación técnica y composición de controles.</td>
</tr>
<tr class="odd">
<td>Ampliado actual</td>
<td>Biopsias</td>
<td style="text-align: right;">130</td>
<td style="text-align: right;">25.718.239</td>
<td>Cohorte de biopsias para el handoff canónico.</td>
</tr>
<tr class="even">
<td>Ampliado actual</td>
<td>Controles negativos</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">4.192.039</td>
<td>Preservados para una evaluación posterior de prevalencia/decontaminación.</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>—</strong></td>
<td style="text-align: right;"><strong>198</strong></td>
<td style="text-align: right;"><strong>59.974.817</strong></td>
<td><strong>Sin descarte en el preprocesamiento.</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La matriz de 16 comprobaciones de preprocesamiento hizo explícita la cadena de custodia de cada ensayo: manifiesto de bibliotecas, inventarios FastQC raw y trimmed, presencia de FASTQ trimmed, conteos pareados raw y trimmed, retención de pares y verificación del recorte por secuencia. Las ocho comprobaciones pasaron en <code>pilot</code> (46 bibliotecas; 92 FASTQ por inventario) y las mismas ocho en <code>current</code> (152 bibliotecas; 304 FASTQ por inventario). El detalle se puede consultar en la <a href="../tables/04_control_calidad_preprocesamiento/Table-4.6-validacion-etapas-preprocesamiento.tsv">matriz de validación de etapas</a>.</p>
</section>
<section id="informes-de-qc-y-multiqc" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="informes-de-qc-y-multiqc"><span class="header-section-number">4.2</span> Informes de QC y MultiQC</h2>
<p>Los informes de FastQC se integraron con MultiQC antes y después del recorte <span class="citation" data-cites="Ewels2016">(<a href="11_referencias.html#ref-Ewels2016" role="doc-biblioref">Ewels et&nbsp;al. 2016</a>)</span>. La versión pública se regenera exclusivamente a partir de copias temporales de los archivos <code>*_fastqc.zip</code>, conserva los nombres técnicos autorizados y excluye las rutas internas de computación. Se puede consultar el <a href="../multiqc/04_control_calidad_preprocesamiento/MultiQC-4.1-fastqc-crudo.html">informe previo al recorte</a> y el <a href="../multiqc/04_control_calidad_preprocesamiento/MultiQC-4.2-fastqc-recortado.html">informe posterior al recorte</a>.</p>
<p>La <a href="#fig-fastqc-raw-profiles" class="quarto-xref">Figura&nbsp;<span>4.1</span></a> presenta los perfiles de calidad de los FASTQ crudos por ensayo, tipo de biblioteca y sentido de lectura. La <a href="#fig-fastqc-trimmed-profiles" class="quarto-xref">Figura&nbsp;<span>4.2</span></a> muestra la misma evaluación después del recorte por secuencia.</p>
<div id="fig-fastqc-raw-profiles" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Perfiles de calidad de los FASTQ crudos para biopsias, controles positivos y controles negativos de los ensayos pilot y current, con paneles separados para R1 y R2.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-raw-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.1-perfiles-calidad-fastq-crudo-por-ensayo.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figura&nbsp;4.1: Perfiles de calidad FastQC de los FASTQ crudos, estratificados por ensayo, tipo de biblioteca y sentido de lectura."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.1-perfiles-calidad-fastq-crudo-por-ensayo.png" class="img-fluid figure-img" alt="Perfiles de calidad de los FASTQ crudos para biopsias, controles positivos y controles negativos de los ensayos pilot y current, con paneles separados para R1 y R2."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-raw-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.1: Perfiles de calidad FastQC de los FASTQ crudos, estratificados por ensayo, tipo de biblioteca y sentido de lectura.
</figcaption>
</figure>
</div>
<div id="fig-fastqc-trimmed-profiles" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Perfiles de calidad de los FASTQ recortados para biopsias, controles positivos y controles negativos de los ensayos pilot y current, con paneles separados para R1 y R2.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-trimmed-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.2-perfiles-calidad-fastq-recortado-por-ensayo.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figura&nbsp;4.2: Perfiles de calidad FastQC de los FASTQ tras el recorte por secuencia, estratificados por ensayo, tipo de biblioteca y sentido de lectura."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.2-perfiles-calidad-fastq-recortado-por-ensayo.png" class="img-fluid figure-img" alt="Perfiles de calidad de los FASTQ recortados para biopsias, controles positivos y controles negativos de los ensayos pilot y current, con paneles separados para R1 y R2."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-trimmed-profiles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.2: Perfiles de calidad FastQC de los FASTQ tras el recorte por secuencia, estratificados por ensayo, tipo de biblioteca y sentido de lectura.
</figcaption>
</figure>
</div>
<p>En estas figuras, <code>pilot</code> separa biopsias y controles positivos, mientras que <code>current</code> separa biopsias y negativos. La comparación raw→trimmed es descriptiva: el recorte se condicionó a evidencia de primer y no fue un filtro de calidad ni de bibliotecas. Por ello, una diferencia de perfil después del recorte no debe leerse como pérdida selectiva de muestras; el contraste de retención y de fusión se evalúa después con DADA2 (<a href="05_dada2_inferencia_asv.html#sec-dada2-filtering" class="quarto-xref"><span>Sección 5.3</span></a>).</p>
</section>
<section id="recorte-y-verificación-de-primers" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="recorte-y-verificación-de-primers"><span class="header-section-number">4.3</span> Recorte y verificación de primers</h2>
<p>Cutadapt 5.2 <span class="citation" data-cites="Martin2011">(<a href="11_referencias.html#ref-Martin2011" role="doc-biblioref">Martin 2011</a>)</span> aplicó cuatro adaptadores terminales completos: 341F (<code>CCTACGGGNGGCWGCAG</code>) anclado a R1-5′ y 805R (<code>GACTACHVGGGTATCTAATCC</code>) anclado a R2-5′, junto con rc805R (<code>GGATTAGATACCCBDGTAGTC</code>) anclado a R1-3′ y rc341F (<code>CTGCWGCCNCCCGTAGG</code>) anclado a R2-3′. Los adaptadores 5′ se expresan como <code>^primer</code> y los RC 3′ como <code>primer$</code>.</p>
<p>Cada coincidencia debía cubrir el primer completo: 17/21 nt en 5′ para R1/R2 y 21/17 nt en 3′ para R1/R2. Se aplicaron tasa máxima de error <code>e=0,15</code>, sin indels y <code>--times 2</code>, de modo que el procedimiento puede comprobar de forma iterativa los extremos configurados. No se usaron <code>-u</code>, <code>-U</code> ni <code>--discard-untrimmed</code>. Por tanto, solo se retiran bases de una coincidencia terminal observada; una lectura sin coincidencia en cualquiera de los extremos se conserva intacta en ese extremo.</p>
<p>La no coincidencia no demuestra ausencia biológica de primer: demuestra únicamente que no existe evidencia configurada para retirar esas bases. Se retuvo el 100 % de los pares en ambos ensayos y los 16 controles formales de preprocesamiento se superaron.</p>
<p>La retención y las coincidencias de primer se detallan en la <a href="#tbl-primer-trimming" class="quarto-xref">Tabla&nbsp;<span>4.3</span></a>.</p>
<div id="tbl-primer-trimming" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-primer-trimming-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.3: Retención de pares y coincidencias completas de los primers 5′ y RC 3′ anclados tras el recorte por secuencia. Las lecturas sin coincidencia terminal se preservaron, sin descartarlas.
</figcaption>
<div aria-describedby="tbl-primer-trimming-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th style="text-align: right;">Pares de entrada</th>
<th style="text-align: right;">Pares de salida</th>
<th style="text-align: right;">Retención</th>
<th style="text-align: right;">341F, R1-5′</th>
<th style="text-align: right;">805R, R2-5′</th>
<th style="text-align: right;">rc805R, R1-3′</th>
<th style="text-align: right;">rc341F, R2-3′</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Piloto</td>
<td style="text-align: right;">30,06 millones</td>
<td style="text-align: right;">30,06 millones</td>
<td style="text-align: right;">100,00 %</td>
<td style="text-align: right;">57,7628 %</td>
<td style="text-align: right;">19,3149 %</td>
<td style="text-align: right;">7,9562 %</td>
<td style="text-align: right;">7,0211 %</td>
</tr>
<tr class="even">
<td>Ampliado actual</td>
<td style="text-align: right;">29,91 millones</td>
<td style="text-align: right;">29,91 millones</td>
<td style="text-align: right;">100,00 %</td>
<td style="text-align: right;">71,9893 %</td>
<td style="text-align: right;">7,5226 %</td>
<td style="text-align: right;">12,9895 %</td>
<td style="text-align: right;">16,3764 %</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Las fracciones sin coincidencia 5′ preservadas fueron 42,2372 % (R1) y 80,6851 % (R2) en el piloto, y 28,0107 % (R1) y 92,4774 % (R2) en el ensayo ampliado. Para los RC 3′ fueron 92,0438 % y 92,9789 % en el piloto, y 87,0105 % y 83,6236 % en el ensayo ampliado, para R1 y R2 respectivamente. Estos valores describen coincidencia terminal bajo la configuración aplicada; no son una clasificación biológica de las lecturas sin coincidencia.</p>
<p>La auditoría raw independiente confirmó la orientación canónica de estas señales. La coocurrencia 5′ 341F@R1 + 805R@R2 fue 13,4864 % en el piloto y 6,6080 % en el ensayo ampliado; la coocurrencia RC 3′ rc805R@R1 + rc341F@R2 fue 3,2383 % y 10,2288 %, respectivamente. Las llamadas 5′ de Cutadapt no excedieron las coincidencias terminales raw del escáner en las 396 comparaciones revisadas. No se exige igualdad exacta porque Cutadapt aplica los cuatro adaptadores iterativamente con <code>--times 2</code>, mientras que el escáner cuenta los patrones raw de forma independiente.</p>
<div id="tbl-primer-orientation-pairing" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-primer-orientation-pairing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.4: Coocurrencia de señales de primer en pares raw. El par canónico 5′ es 341F@R1 + 805R@R2; el par canónico RC 3′ es rc805R@R1 + rc341F@R2. Las orientaciones invertidas son los pares intercambiados equivalentes.
</figcaption>
<div aria-describedby="tbl-primer-orientation-pairing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th style="text-align: right;">Par canónico 5′</th>
<th style="text-align: right;">Par 5′ invertido</th>
<th style="text-align: right;">Par canónico RC 3′</th>
<th style="text-align: right;">Par RC 3′ invertido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Piloto</td>
<td style="text-align: right;">13,4864 %</td>
<td style="text-align: right;">0,0032 %</td>
<td style="text-align: right;">3,2383 %</td>
<td style="text-align: right;">0,0003 %</td>
</tr>
<tr class="even">
<td>Ampliado actual</td>
<td style="text-align: right;">6,6080 %</td>
<td style="text-align: right;">0,0004 %</td>
<td style="text-align: right;">10,2288 %</td>
<td style="text-align: right;">0,0006 %</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La diferencia entre los pares canónicos e invertidos de la <a href="#tbl-primer-orientation-pairing" class="quarto-xref">Tabla&nbsp;<span>4.4</span></a> aporta evidencia técnica de orientación, no una asignación taxonómica. En particular, la señal RC 3′ canónica es compatible con <em>read-through</em> y motivó incorporar ambos complementarios inversos al método final. El recorte retiró 1.081.443.452 bases en total (503.286.462 en <code>pilot</code> y 578.156.990 en <code>current</code>) sin perder un solo par. La tabla completa de esta auditoría se publica como <a href="../tables/04_control_calidad_preprocesamiento/Table-4.2-orientacion-pareada-primers.tsv">orientación pareada de primers</a>, junto con la <a href="../tables/04_control_calidad_preprocesamiento/Table-4.2-verificacion-primers-por-secuencia.tsv">verificación por secuencia</a>.</p>
<p>Las métricas reproducibles se encuentran en <a href="../tables/04_control_calidad_preprocesamiento/Table-4.2-retencion-primers-por-ensayo.tsv">retención por ensayo</a> y <a href="../tables/04_control_calidad_preprocesamiento/Table-4.2-verificacion-primers-por-secuencia.tsv">verificación de primers por secuencia</a>.</p>
</section>
<section id="exploración-y-elección-de-la-estrategia-de-recorte" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="exploración-y-elección-de-la-estrategia-de-recorte"><span class="header-section-number">4.4</span> Exploración y elección de la estrategia de recorte</h2>
<p>La estrategia no se eligió por la mera posición esperada de los oligos. Se validaron primero el manifiesto técnico y la correspondencia de los 198 pares R1/R2, y se contrastó el recorte fijo histórico de 17 nt en R1 y 21 nt en R2 con la búsqueda de primers completos en los extremos de cada lectura. El recorte fijo conserva una sensibilidad aislada y reproducible; no es el input de la rama canónica.</p>
<div id="tbl-trimming-branch-role" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-trimming-branch-role-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.5: Ramas que se distinguen a lo largo del informe. La comparación fijo/anclado mantiene DADA2 3/5 para no confundir la estrategia de recorte con el filtro final <code>strict</code> 2/4.
</figcaption>
<div aria-describedby="tbl-trimming-branch-role-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Rama</th>
<th>Regla de recorte</th>
<th>DADA2 asociado</th>
<th>Uso editorial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Canónica</td>
<td>Búsqueda anclada 341F/805R en 5′ y RC en 3′</td>
<td><code>strict</code> 2/4</td>
<td>Tabla final para taxonomía y etapas posteriores autorizadas.</td>
</tr>
<tr class="even">
<td>Sensibilidad anclada</td>
<td>El mismo recorte anclado</td>
<td>3/5</td>
<td>Comparación controlada con el recorte fijo.</td>
</tr>
<tr class="odd">
<td>Sensibilidad fija</td>
<td>17 nt de R1 y 21 nt de R2 en todas las lecturas</td>
<td>3/5</td>
<td>Referencia histórica aislada; no tabla principal.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>El motivo de descartarlo como estrategia principal es metodológico: cortar 17/21 bases en todas las lecturas presupone que esas posiciones contienen el primer, incluso cuando no se observa una coincidencia terminal configurada. La búsqueda anclada elimina bases sólo ante esa evidencia y, además, la auditoría de orientación mostró la señal canónica de <em>read-through</em> en los extremos 3′. La coocurrencia rc805R@R1-3′ + rc341F@R2-3′ fue 3,2383 % en <code>pilot</code> y 10,2288 % en <code>current</code>, frente a 0,0003 % y 0,0006 % para la orientación invertida. Esto justificó incorporar los reversos complementarios 3′ al método final.</p>
<p>La comparación posterior de estrategias se mantuvo deliberadamente aislada: ambas se procesaron con DADA2 <code>maxEE=c(3,5)</code> para atribuir la diferencia al recorte y no al filtro. El fijo produjo más ASVs, pero el anclado alcanzó mayor fracción de lecturas asignadas a género (89,88 % frente a 79,85 % en <code>pilot</code>; 75,07 % frente a 62,61 % en <code>current</code>). La comparación no permite separar el efecto de cada componente del protocolo —corte posicional universal frente a búsqueda anclada y tratamiento de RC 3′— ni afirmar que cada ASV adicional del fijo sea un artefacto. Sí aporta una razón cuantitativa para preferir una rama principal conservadora, que se desarrolla en el <a href="../chapters/05_dada2_inferencia_asv.html#sec-fixed-anchored-comparison">capítulo DADA2</a>. La tabla principal usa, por ello, el recorte anclado y la selección final <code>strict</code> 2/4.</p>
</section>
<section id="profundidad-de-secuenciación-de-las-biopsias-repetidas" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="profundidad-de-secuenciación-de-las-biopsias-repetidas"><span class="header-section-number">4.5</span> Profundidad de secuenciación de las biopsias repetidas</h2>
<p>La comparación pareada utiliza las ocho biopsias presentes en el piloto y el ensayo ampliado. Se trata de una comparación técnica de FASTQ crudos antes de filtrado, fusión de pares o eliminación de quimeras. En todas ellas, la profundidad de entrada fue mayor en el piloto; la media geométrica del cociente piloto/ampliado fue 7,69 y la mediana 7,51. No se aplicó una prueba de hipótesis.</p>
<p>El resumen descriptivo de esta comparación se presenta en la <a href="#tbl-repeated-depth-summary" class="quarto-xref">Tabla&nbsp;<span>4.6</span></a>.</p>
<div id="tbl-repeated-depth-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-repeated-depth-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.6: Profundidad de los pares de lecturas crudos en las biopsias repetidas.
</figcaption>
<div aria-describedby="tbl-repeated-depth-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica (8 biopsias emparejadas)</th>
<th style="text-align: right;">Piloto</th>
<th style="text-align: right;">Ampliado actual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pares totales</td>
<td style="text-align: right;">11,82 millones</td>
<td style="text-align: right;">1,55 millones</td>
</tr>
<tr class="even">
<td>Media por biopsia, DE</td>
<td style="text-align: right;">1,48 (0,26) millones</td>
<td style="text-align: right;">0,19 (0,04) millones</td>
</tr>
<tr class="odd">
<td>Mediana por biopsia [RIC]</td>
<td style="text-align: right;">1,48 [1,44–1,58] millones</td>
<td style="text-align: right;">0,20 [0,16–0,22] millones</td>
</tr>
<tr class="even">
<td>Rango por biopsia</td>
<td style="text-align: right;">0,94–1,84 millones</td>
<td style="text-align: right;">0,14–0,26 millones</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>La <a href="#fig-repeated-depth" class="quarto-xref">Figura&nbsp;<span>4.3</span></a> muestra pares de lecturas en escala logarítmica. Cada línea une la misma biopsia entre ambos ensayos; el eje vertical está expresado en millones de pares, no en lecturas individuales.</p>
<div id="fig-repeated-depth" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Gráfico de líneas pareadas que compara la profundidad de las ocho biopsias repetidas entre el piloto y el ensayo ampliado.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-repeated-depth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.3-profundidad-biopsias-repetidas.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figura&nbsp;4.3: Profundidad de secuenciación de las ocho biopsias repetidas. Cada línea representa una biopsia; el eje vertical está en escala logarítmica y expresa millones de pares de lecturas."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.3-profundidad-biopsias-repetidas.png" class="img-fluid figure-img" alt="Gráfico de líneas pareadas que compara la profundidad de las ocho biopsias repetidas entre el piloto y el ensayo ampliado."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-repeated-depth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.3: Profundidad de secuenciación de las ocho biopsias repetidas. Cada línea representa una biopsia; el eje vertical está en escala logarítmica y expresa millones de pares de lecturas.
</figcaption>
</figure>
</div>
<p>Los valores técnicos individuales y el resumen se ofrecen en la <a href="../tables/04_control_calidad_preprocesamiento/Table-4.3-profundidad-biopsias-repetidas.tsv">tabla por biopsia</a> y en el <a href="../tables/04_control_calidad_preprocesamiento/Table-4.3-resumen-profundidad-biopsias-repetidas.tsv">resumen descriptivo</a>.</p>
</section>
<section id="auditoría-integral-de-fastqcmultiqc" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="auditoría-integral-de-fastqcmultiqc"><span class="header-section-number">4.6</span> Auditoría integral de FastQC/MultiQC</h2>
<p>La auditoría vuelve a leer los 396 informes FastQC de FASTQ crudos y los 396 informes posteriores al recorte, sin ejecutar FastQC, Cutadapt, DADA2 ni etapas posteriores. Para cada etapa se comprobaron los 11 módulos que muestra MultiQC, las estadísticas básicas y los estados frente a los informes de <code>pilot</code> y <code>current</code>. Los 16 controles de esta comprobación (cobertura de informes, profundidad y estadísticas básicas, estados de módulo y perfiles Phred, por etapa y ensayo) resultaron conformes. Los perfiles Phred ya informados se reprodujeron a la precisión histórica de tres decimales.</p>
<p>Las cifras siguientes son intervalos de las medianas por biblioteca entre los 16 grupos públicos (etapa, ensayo, tipo de biblioteca y R1/R2); no exponen métricas por biblioteca. El detalle completo, con mediana, P10, P90, mínimo y máximo, puede descargarse en el <a href="../tables/04_control_calidad_preprocesamiento/Table-4.4-resumen-cuantitativo-modulos-fastqc.tsv">resumen cuantitativo de módulos FastQC</a>.</p>
<div id="tbl-fastqc-audit-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fastqc-audit-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.7: Indicadores FastQC agregados por grupo. Los intervalos corresponden al rango de las medianas de biblioteca de los grupos públicos, no al rango de lecturas individuales.
</figcaption>
<div aria-describedby="tbl-fastqc-audit-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Indicador agregado</th>
<th style="text-align: right;">Crudos</th>
<th style="text-align: right;">Recortados</th>
<th>Lectura descriptiva</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Informes y módulos comprobados</td>
<td style="text-align: right;">396; 11/11</td>
<td style="text-align: right;">396; 11/11</td>
<td>Cobertura completa de R1 y R2.</td>
</tr>
<tr class="even">
<td>Calidad media por secuencia (Phred)</td>
<td style="text-align: right;">Q33,31–Q36,99</td>
<td style="text-align: right;">Q33,36–Q37,19</td>
<td>La distribución por lectura permanece alta en las medianas de grupo.</td>
</tr>
<tr class="odd">
<td>Lecturas con calidad media ≤ Q20</td>
<td style="text-align: right;">0,90–4,27 %</td>
<td style="text-align: right;">1,04–4,27 %</td>
<td>Se conserva como diagnóstico de la cola de calidad.</td>
</tr>
<tr class="even">
<td>Longitud mediana</td>
<td style="text-align: right;">301 nt</td>
<td style="text-align: right;">284,5–301 nt</td>
<td>El recorte es por coincidencia de primer; por ello persiste longitud variable.</td>
</tr>
<tr class="odd">
<td>%GC de estadísticas básicas</td>
<td style="text-align: right;">50,0–55,0 %</td>
<td style="text-align: right;">50,0–55,0 %</td>
<td>Se interpreta junto con la distribución de GC del amplicón.</td>
</tr>
<tr class="even">
<td>Máximo contenido de N por ciclo</td>
<td style="text-align: right;">1,14–50,57 %</td>
<td style="text-align: right;">0,89–47,95 %</td>
<td>Los máximos terminales, especialmente en R2, son una señal diagnóstica explícita.</td>
</tr>
<tr class="odd">
<td>Lecturas duplicadas; sobrerrepresentadas</td>
<td style="text-align: right;">2,60–93,25 %; 0–65,33 %</td>
<td style="text-align: right;">9,42–94,90 %; 3,95–77,93 %</td>
<td>Compatibles con la estructura de una biblioteca de amplicones; no son una regla de exclusión.</td>
</tr>
<tr class="even">
<td>Máximo contenido de adaptador</td>
<td style="text-align: right;">0,37–7,08 %</td>
<td style="text-align: right;">0,37–7,08 %</td>
<td>Se mantiene visible para seguimiento técnico.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="estados-fastqc-y-alcance-de-cada-módulo" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="estados-fastqc-y-alcance-de-cada-módulo"><span class="header-section-number">4.6.1</span> Estados FastQC y alcance de cada módulo</h3>
<p>La <a href="#fig-fastqc-module-status" class="quarto-xref">Figura&nbsp;<span>4.4</span></a> conserva literalmente los estados <code>pass</code>, <code>warn</code> y <code>fail</code>. Por ejemplo, <em>Basic Statistics</em> fue <code>pass</code> en los 396 informes de cada etapa; <em>Per sequence quality scores</em> fue <code>pass</code> en 385/396 crudos y 385/396 recortados. En cambio, la composición de bases fue <code>fail</code> en todos los informes; la distribución de longitudes fue <code>warn</code> en los 396 raw y, tras el recorte por coincidencia, <code>warn</code> en 37 y <code>fail</code> en 359 informes. Estos últimos estados describen las características de las lecturas 16S y del método de recorte; no constituyen por sí mismos una decisión de descarte.</p>
<div id="fig-fastqc-module-status" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Matriz de los once módulos FastQC. Las columnas separan crudo y recortado, ensayo, tipo de biblioteca y R1/R2; cada celda muestra conteos pass, warn y fail.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-module-status-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.4-estados-modulos-fastqc-por-etapa.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figura&nbsp;4.4: Estados FastQC agregados por etapa, ensayo, tipo de biblioteca y lectura. Cada celda contiene el número de informes pass/warn/fail y el color indica el peor estado presente."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.4-estados-modulos-fastqc-por-etapa.png" class="img-fluid figure-img" alt="Matriz de los once módulos FastQC. Las columnas separan crudo y recortado, ensayo, tipo de biblioteca y R1/R2; cada celda muestra conteos pass, warn y fail."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-module-status-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.4: Estados FastQC agregados por etapa, ensayo, tipo de biblioteca y lectura. Cada celda contiene el número de informes pass/warn/fail y el color indica el peor estado presente.
</figcaption>
</figure>
</div>
<p>La <a href="../tables/04_control_calidad_preprocesamiento/Table-4.5-estados-modulos-fastqc.tsv">matriz descargable de estados FastQC</a> contiene los conteos y porcentajes por grupo. La <a href="#tbl-fastqc-modules" class="quarto-xref">Tabla&nbsp;<span>4.8</span></a> explica el valor conservado para cada uno de los 11 módulos y su lectura en este diseño.</p>
<div id="tbl-fastqc-modules" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fastqc-modules-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.8: Cobertura de los 11 módulos FastQC y lectura contextualizada. Los estados se mantienen literalmente en la matriz descargable.
</figcaption>
<div aria-describedby="tbl-fastqc-modules-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Módulo FastQC</th>
<th>Valor agregado conservado</th>
<th>Interpretación en amplicones 16S</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Basic Statistics</td>
<td>Lecturas, bases, %GC, lecturas de baja calidad y rango de longitud</td>
<td>Verifica profundidad y consistencia de los inputs; no hubo pérdida de pares.</td>
</tr>
<tr class="even">
<td>Per base sequence quality</td>
<td>Media, mediana, P10/P90 y cuartiles Phred por ciclo</td>
<td>Localiza ciclos con menor calidad y se consulta con el perfil, sin fijar aquí truncamientos.</td>
</tr>
<tr class="odd">
<td>Per tile sequence quality</td>
<td>Máxima desviación media por tile</td>
<td>Señala heterogeneidad espacial potencial; es diagnóstico de instrumento, no una exclusión automática.</td>
</tr>
<tr class="even">
<td>Per sequence quality scores</td>
<td>Calidad media por lectura y fracciones ≤Q20/≤Q30</td>
<td>Resume la distribución de calidad por lectura más allá de un ciclo concreto.</td>
</tr>
<tr class="odd">
<td>Per base sequence content</td>
<td>Máximo desequilibrio entre A/C/G/T</td>
<td>El sesgo inicial de bases puede reflejar primers y diseño de amplicón; <code>fail</code> no equivale a muestra inválida.</td>
</tr>
<tr class="even">
<td>Per sequence GC content</td>
<td>Media y P10–P90 de GC por secuencia</td>
<td>Una distribución no normal es esperable en comunidades y controles de 16S; se conserva para detectar desviaciones.</td>
</tr>
<tr class="odd">
<td>Per base N content</td>
<td>Máximo porcentaje de N por ciclo</td>
<td>Hace visible la incertidumbre de bases, incluida la señal terminal observada en algunos grupos R2.</td>
</tr>
<tr class="even">
<td>Sequence Length Distribution</td>
<td>Longitud mínima, media, mediana y máxima</td>
<td>El intervalo variable documenta qué lecturas coincidieron con los primers terminales configurados; no supone recorte posicional.</td>
</tr>
<tr class="odd">
<td>Sequence Duplication Levels</td>
<td>Fracción deduplicada/duplicada y con nivel &gt;10</td>
<td>La duplicación alta puede ser inherente a amplicones y a controles; requiere contexto, no descarte automático.</td>
</tr>
<tr class="even">
<td>Overrepresented sequences</td>
<td>Fracción total y fracción de la secuencia principal</td>
<td>Puede reflejar amplicones, primers o controles; se muestra como señal, sin clasificarla como contaminante.</td>
</tr>
<tr class="odd">
<td>Adapter Content</td>
<td>Máximo porcentaje de adaptador</td>
<td>Permite vigilar contenido residual de adaptadores sin modificar el procedimiento aplicado.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="calidad-longitud-y-composición" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="calidad-longitud-y-composición"><span class="header-section-number">4.6.2</span> Calidad, longitud y composición</h3>
<p>La <a href="#fig-fastqc-quality-length" class="quarto-xref">Figura&nbsp;<span>4.5</span></a> resume la calidad media de las lecturas, la fracción con calidad media baja y las longitudes. Las medianas de calidad media por secuencia se sitúan entre Q33,31 y Q36,99 en crudos y entre Q33,36 y Q37,19 tras el recorte. La longitud mediana pasa de 301 nt a 284,5–301 nt: es el patrón esperado de un recorte condicionado a coincidencias de 341F/805R y sus RC terminales, no un indicador de que todas las lecturas se hayan acortado por posición fija.</p>
<div id="fig-fastqc-quality-length" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cuatro paneles de barras con calidad media por lectura, porcentaje de lecturas con calidad media menor o igual a Q20, longitud mediana y longitud mínima; naranja crudo y azul recortado.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-quality-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.5-calidad-por-secuencia-y-longitud-fastqc.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figura&nbsp;4.5: Calidad por secuencia y longitudes FastQC agregadas por etapa y grupo técnico."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.5-calidad-por-secuencia-y-longitud-fastqc.png" class="img-fluid figure-img" alt="Cuatro paneles de barras con calidad media por lectura, porcentaje de lecturas con calidad media menor o igual a Q20, longitud mediana y longitud mínima; naranja crudo y azul recortado."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-quality-length-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.5: Calidad por secuencia y longitudes FastQC agregadas por etapa y grupo técnico.
</figcaption>
</figure>
</div>
</section>
<section id="por-qué-no-se-truncó-por-posición" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="por-qué-no-se-truncó-por-posición"><span class="header-section-number">4.6.3</span> Por qué no se truncó por posición</h3>
<p>La calidad no justificó imponer una longitud única antes del denoising. En los FASTQ recortados, a 250 nt todas las bibliotecas cumplen simultáneamente calidad media por lectura ≥Q30 y cuartil inferior ≥Q20; sin embargo, el P10 de la fracción de lecturas que alcanza esa longitud ya es 46,39 % (R1) y 46,74 % (R2) en <code>pilot</code>, frente a 73,24 % y 76,81 % en <code>current</code>. A 280 nt desciende a 44,30 % y 38,38 % en <code>pilot</code>, y a 64,52 % y 63,31 % en <code>current</code>.</p>
<div id="tbl-truncation-diagnostic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-truncation-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;4.9: Diagnóstico de longitud alcanzada tras el recorte anclado. La calidad en los puntos 250 y 280 nt cumple los umbrales indicados en todas las bibliotecas; el P10 describe el extremo inferior de la distribución entre bibliotecas.
</figcaption>
<div aria-describedby="tbl-truncation-diagnostic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Ensayo</th>
<th>Mate</th>
<th style="text-align: right;">P10 de lecturas ≥250 nt</th>
<th style="text-align: right;">P10 de lecturas ≥280 nt</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Piloto</td>
<td>R1</td>
<td style="text-align: right;">46,39 %</td>
<td style="text-align: right;">44,30 %</td>
<td>Un corte fijo perdería una fracción heterogénea de lecturas aunque la calidad siga siendo alta.</td>
</tr>
<tr class="even">
<td>Piloto</td>
<td>R2</td>
<td style="text-align: right;">46,74 %</td>
<td style="text-align: right;">38,38 %</td>
<td>La pérdida potencial es mayor en el extremo de 280 nt.</td>
</tr>
<tr class="odd">
<td>Ampliado actual</td>
<td>R1</td>
<td style="text-align: right;">73,24 %</td>
<td style="text-align: right;">64,52 %</td>
<td>Conserva más longitud que <code>pilot</code>, por lo que no comparte un punto de corte natural.</td>
</tr>
<tr class="even">
<td>Ampliado actual</td>
<td>R2</td>
<td style="text-align: right;">76,81 %</td>
<td style="text-align: right;">63,31 %</td>
<td>La variación entre ensayos y mates desaconseja un truncamiento posicional común.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Por esta razón la configuración final usó <code>truncLen=c(0,0)</code>: conserva la longitud variable y deja que <code>minOverlap=20</code>, <code>maxMismatch=0</code> y la evaluación de fusión de DADA2 impongan el requisito de solapamiento real. La serie completa de posiciones candidatas está disponible en la <a href="../tables/04_control_calidad_preprocesamiento/Table-4.7-candidatos-truncamiento-fastqc.tsv">tabla de diagnóstico de truncamiento</a>; los resultados de filtros y fusión se desarrollan en el capítulo 5.</p>
<p>La <a href="#fig-fastqc-composition-gc-n" class="quarto-xref">Figura&nbsp;<span>4.6</span></a> muestra el desequilibrio de bases, GC y N. El desequilibrio máximo de A/C/G/T de las medianas de grupo es 62,92–99,24 % en raw y 60,86–90,98 % tras el recorte; junto con los estados de composición/GC, no se usa como filtro porque es compatible con la preparación de bibliotecas 16S. La señal de N máxima llega a 50,57 % en crudos y 47,95 % tras el recorte en grupos R2; se identifica como un patrón terminal que debe seguirse aguas abajo, no como autorización para retirar bibliotecas o modificar DADA2.</p>
<div id="fig-fastqc-composition-gc-n" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cuatro paneles con desequilibrio máximo de bases, porcentaje GC, intervalo P10-P90 de GC por secuencia y máximo contenido de N, para grupos crudos y recortados.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-composition-gc-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.6-composicion-gc-y-n-fastqc.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figura&nbsp;4.6: Composición de bases, GC y contenido de N de FastQC agregados por etapa y grupo técnico."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.6-composicion-gc-y-n-fastqc.png" class="img-fluid figure-img" alt="Cuatro paneles con desequilibrio máximo de bases, porcentaje GC, intervalo P10-P90 de GC por secuencia y máximo contenido de N, para grupos crudos y recortados."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-composition-gc-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.6: Composición de bases, GC y contenido de N de FastQC agregados por etapa y grupo técnico.
</figcaption>
</figure>
</div>
</section>
<section id="duplicación-secuencias-sobrerrepresentadas-y-adaptadores" class="level3" data-number="4.6.4">
<h3 data-number="4.6.4" class="anchored" data-anchor-id="duplicación-secuencias-sobrerrepresentadas-y-adaptadores"><span class="header-section-number">4.6.4</span> Duplicación, secuencias sobrerrepresentadas y adaptadores</h3>
<p>La <a href="#fig-fastqc-technical-signals" class="quarto-xref">Figura&nbsp;<span>4.7</span></a> presenta señales que FastQC suele marcar en amplicones. Las medianas de duplicación alcanzan 93,25 % en crudos y 94,90 % tras el recorte; las de secuencias sobrerrepresentadas alcanzan 65,33 % y 77,93 %, respectivamente. Estas proporciones se reportan para transparentar la complejidad de biblioteca y los controles, no para deduplicar ni excluir por esta auditoría. El máximo de adaptadores se mantiene entre 0,37 y 7,08 % según grupo y etapa.</p>
<div id="fig-fastqc-technical-signals" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Cuatro paneles de barras con porcentaje de lecturas duplicadas, porcentaje con nivel de duplicación mayor que diez, secuencias sobrerrepresentadas y máximo contenido de adaptadores; naranja crudo y azul recortado.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastqc-technical-signals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../figures/04_control_calidad_preprocesamiento/Fig-4.7-duplicacion-sobrerrepresentadas-y-adaptadores-fastqc.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figura&nbsp;4.7: Duplicación, secuencias sobrerrepresentadas y contenido de adaptadores FastQC agregados por etapa y grupo técnico."><img src="../figures/04_control_calidad_preprocesamiento/Fig-4.7-duplicacion-sobrerrepresentadas-y-adaptadores-fastqc.png" class="img-fluid figure-img" alt="Cuatro paneles de barras con porcentaje de lecturas duplicadas, porcentaje con nivel de duplicación mayor que diez, secuencias sobrerrepresentadas y máximo contenido de adaptadores; naranja crudo y azul recortado."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastqc-technical-signals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4.7: Duplicación, secuencias sobrerrepresentadas y contenido de adaptadores FastQC agregados por etapa y grupo técnico.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Uso de esta auditoría
</div>
</div>
<div class="callout-body-container callout-body">
<p>La auditoría es descriptiva y trazable: aporta valores y señales diagnósticas para las etapas raw y trimmed, pero no aprueba por sí misma filtros, truncamientos ni exclusiones. La decisión DADA2 posterior se documenta en el capítulo 5 y se basó adicionalmente en retención, fusión, quimeras y profundidad de controles.</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Precaución</span>Criterios de exclusión
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dos biopsias de profundidad muy baja se conservaron tras DADA2 (18 y 48 lecturas no quiméricas, respectivamente). Su posible exclusión no se decidirá a partir del FASTQ crudo ni de esta auditoría de forma aislada: requiere una etapa autorizada de QC conjunto, controles y un umbral explícito antes de cualquier análisis downstream.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Ewels2016" class="csl-entry" role="listitem">
Ewels, Philip, Måns Magnusson, Sverker Lundin, y Max Käller. 2016. <span>«MultiQC: Summarize analysis results for multiple tools and samples in a single report»</span>. <em>Bioinformatics</em> 32 (19): 3047-48. <a href="https://doi.org/10.1093/bioinformatics/btw354">https://doi.org/10.1093/bioinformatics/btw354</a>.
</div>
<div id="ref-Martin2011" class="csl-entry" role="listitem">
Martin, Marcel. 2011. <span>«Cutadapt removes adapter sequences from high-throughput sequencing reads»</span>. <em>EMBnet.journal</em> 17 (1): 10-12. <a href="https://doi.org/10.14806/ej.17.1.200">https://doi.org/10.14806/ej.17.1.200</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/dcosimber\.github\.io\/carpio2\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/03_flujo_bioinformatico.html" class="pagination-link" aria-label="Flujo bioinformático">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Flujo bioinformático</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/05_dada2_inferencia_asv.html" class="pagination-link" aria-label="DADA2 e inferencia de ASV">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">DADA2 e inferencia de ASV</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dcosimber/carpio2/blob/main/chapters/04_control_calidad_preprocesamiento.qmd" class="toc-action"><i class="bi bi-github"></i>Ver el código</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>